#!/bin/bash
# Deploy Module 4 Demo Infrastructure
# Usage: ./scripts/deploy.sh [deploy|destroy]

set -e

REGION="${AWS_DEFAULT_REGION:-ap-southeast-1}"
STACK_PREFIX="m4-demo"
ALERT_EMAIL="${ALERT_EMAIL:-demo-alerts@example.com}"

ACTION="${1:-deploy}"

echo "=============================================="
echo " Module 4: Observability Demo Infrastructure"
echo " Region: $REGION"
echo " Action: $ACTION"
echo "=============================================="

if [ "$ACTION" == "destroy" ]; then
    echo ""
    echo "⚠️  Destroying all stacks..."
    for STACK in "${STACK_PREFIX}-dashboard" "${STACK_PREFIX}-alarms" "${STACK_PREFIX}-observability"; do
        echo "  Deleting $STACK..."
        aws cloudformation delete-stack --stack-name "$STACK" --region "$REGION" 2>/dev/null || true
        aws cloudformation wait stack-delete-complete --stack-name "$STACK" --region "$REGION" 2>/dev/null || true
        echo "  ✓ $STACK deleted"
    done
    echo ""
    echo "✅ All stacks destroyed."
    exit 0
fi

echo ""
echo "📦 Deploying stacks..."
echo ""

# 1. Observability (Log Groups + DynamoDB)
echo "  [1/3] Observability resources..."
aws cloudformation deploy \
    --template-file infra/cfn-observability.yaml \
    --stack-name "${STACK_PREFIX}-observability" \
    --region "$REGION" \
    --no-fail-on-empty-changeset \
    --tags Project=mladas-module4-demo
echo "  ✓ Log groups and evaluation table deployed"

# 2. Alarms
echo "  [2/3] CloudWatch Alarms + SNS..."
aws cloudformation deploy \
    --template-file infra/cfn-alarms.yaml \
    --stack-name "${STACK_PREFIX}-alarms" \
    --region "$REGION" \
    --parameter-overrides AlertEmail="$ALERT_EMAIL" \
    --no-fail-on-empty-changeset \
    --tags Project=mladas-module4-demo
echo "  ✓ Alarms and SNS topic deployed"

# 3. Dashboard
echo "  [3/3] CloudWatch Dashboard..."
aws cloudformation deploy \
    --template-file infra/cfn-dashboard.yaml \
    --stack-name "${STACK_PREFIX}-dashboard" \
    --region "$REGION" \
    --parameter-overrides Region="$REGION" \
    --no-fail-on-empty-changeset \
    --tags Project=mladas-module4-demo
echo "  ✓ Dashboard deployed"

# Get outputs
DASHBOARD_URL=$(aws cloudformation describe-stacks \
    --stack-name "${STACK_PREFIX}-dashboard" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='DashboardUrl'].OutputValue" \
    --output text)

ALERT_TOPIC=$(aws cloudformation describe-stacks \
    --stack-name "${STACK_PREFIX}-alarms" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='AlertTopicArn'].OutputValue" \
    --output text)

# Write config
cat > config.env << EOF
# Module 4 Demo Configuration (auto-generated by deploy.sh)
export AWS_REGION="$REGION"
export METRICS_NAMESPACE="m4-demo/AgentMetrics"
export SPANS_LOG_GROUP="/m4-demo/agent-spans"
export METRICS_LOG_GROUP="/m4-demo/agent-metrics"
export LOOP_LOG_GROUP="/m4-demo/loop-detection"
export EVAL_LOG_GROUP="/m4-demo/evaluations"
export EVAL_TABLE="m4-demo-evaluations"
export ALERT_TOPIC_ARN="$ALERT_TOPIC"
export DASHBOARD_URL="$DASHBOARD_URL"
EOF

echo ""
echo "=============================================="
echo " ✅ DEPLOYMENT COMPLETE"
echo "=============================================="
echo ""
echo "  Dashboard: $DASHBOARD_URL"
echo "  Alert Topic: $ALERT_TOPIC"
echo "  Alert Email: $ALERT_EMAIL (confirm subscription in your inbox)"
echo ""
echo "  Config written to: config.env"
echo "  To use: source config.env && python part1_tracing.py"
echo ""
